### ISSUE TITLE
bugs in your code

### ISSUE THREAD

**Issue by jichilen** [diggerdu/Generalized-Intersection-over-Union#1]
https://github.com/diggerdu/Generalized-Intersection-over-Union/blob/cde90fc0d43a89ade10d22898b22786ebdcc1cf8/bbox_overlaps.py#L100

however in paper: $$GIoU=IoU-\frac{C\\(A\cupB)}{C}$$

may be (closure - union) is the right choice

**Comment by diggerdu** [comment]
抱歉 是我搞错了 谢谢提醒
